### ISSUE TITLE
Create tagHelper javascript dynamically.

### ISSUE THREAD

**Issue by brucnj** [maliming/reCAPTCHA#11]
Hello! 
Is it possible to use tagHelper javascript when a partial view is opened (a dynamic modal for example)?

I couldn't make the tag (`<recaptcha-script-v3-js />`) be loaded into a dynamic component. I am currently using .Net 5 MVC and jQuery.

**Comment by maliming** [comment]
hi @brucnj 

Can you share a demo project?

**Comment by brucnj** [comment]
Here is a demo project with the problem :)
[TagHelperDynamically.zip](https://github.com/maliming/reCAPTCHA/files/6750546/TagHelperDynamically.zip)

I managed to find a solution by adding the tag "`<recaptcha-script-v3 />`" on the page that would load the Partial View, but it's still not 100% because when I add the tag on the _Layout.cshtml page, for example, the reCAPTCHA iframe appears constantly.
