### ISSUE TITLE
reCAPTCHA v3 Timeout

### ISSUE THREAD

**Issue by DamienLaw** [maliming/reCAPTCHA#4]
In order to reproduce this, run the demo for v3. After the page has been loaded, DO NOT click on the **submit** button yet. Wait for more than 2 minutes before clicking the button. You will receive a _timeout-or-duplicate_ error.

![image](https://user-images.githubusercontent.com/14930009/94887288-8fe37f00-04a8-11eb-9623-66b58fe448ba.png)

From Google reCAPTCHA v3 documentation at [https://developers.google.com/recaptcha/docs/v3](url)

![image](https://user-images.githubusercontent.com/14930009/94887345-b1446b00-04a8-11eb-95cc-64f329a68ecd.png)

It is very common for a user taking more than 2 minutes to fill up long registration forms.

**Comment by maliming** [comment]
hi @DamienLaw 

Thanks for the feedback I will check this.

**Comment by maliming** [comment]
hi @DamienLaw 
Please try the `0.3.1` version.

https://github.com/maliming/reCAPTCHA/blob/master/demo/reCAPTCHA.Demo/Pages/V3_Programmatically.cshtml

https://www.nuget.org/packages/Owl.reCAPTCHA/0.3.1
